import json
import re

input_file = "lib/l10n/app_en.arb"
output_file = "lib/l10n/localization_extension.dart"

def big_first_letter(name):
    return name[0].upper() + name[1:]

def snake_to_camel(name):
    components = name.split('_')
    return components[0] + ''.join(big_first_letter(x) for x in components[1:])

with open(input_file, 'r') as f:
    data = json.load(f)

with open(output_file, 'w') as f:
    f.write("// GENERATED BY l10n.py. DO NOT MODIFY!\n\n")
    f.write("import 'package:flutter/material.dart';\n")
    f.write("import 'package:flutter_gen/gen_l10n/app_localizations.dart';\n\n")
    f.write("extension LocalizationExtension on BuildContext {\n")

    for key in data.keys():
        camel_key = snake_to_camel(key)
        f.write(f"  String get {camel_key} => AppLocalizations.of(this)?.{key} ?? '';\n")

    f.write("}\n")