name: anx_reader
description: "A e-book reader."
publish_to: 'none'

version: 1.0.1+104

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  file_picker: ^8.0.0+1
  path_provider: ^2.1.2
  epub_view: ^3.2.0
  image_picker: ^1.0.7
  image: ^3.3.0
#  image: ^4.1.7
  sqflite: ^2.3.2
  path: ^1.9.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  flutter_gen_runner: ^5.4.0
  intl: ^0.18.1
  settings_ui: ^2.0.2
  flutter_colorpicker: ^1.0.3
  epubx: ^4.0.0
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2
  archive: ^3.4.10
  flutter_inappwebview: ^6.0.0
  shelf: ^1.4.1
  fl_chart: ^0.67.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10
  permission_handler: ^11.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: any
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icon/Markdown.svg
    - assets/js/epub.min.js
    - assets/js/epub.js
    - assets/js/jszip.min.js
    - assets/fonts/SourceHanSerifSC-Regular.otf


  fonts:
    - family: SourceHanSerif
      fonts:
        - asset: assets/fonts/SourceHanSerifSC-Regular.otf

