name: anx_reader
description: "An e-book reader."
publish_to: 'none'

version: 1.1.8+2029

environment:
  sdk: '>=3.5.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  file_picker: ^8.1.2
  path_provider: ^2.1.2
  image: ^3.0.8
  sqflite: ^2.3.2
  path: ^1.9.0
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  flutter_gen_runner: ^5.4.0
  intl: ^0.19.0
  settings_ui: ^2.0.2
  flutter_colorpicker: ^1.0.3
  html: ^0.15.4
  flutter_html: ^3.0.0-beta.2
  archive: ^3.4.10
  flutter_inappwebview: ^6.0.0
  shelf: ^1.4.1
  fl_chart: ^0.67.0
  flutter_rating_bar: ^4.0.1
  permission_handler: ^11.3.1
  webdav_client: ^1.2.1
  fluttertoast: ^8.2.6
  dio: ^5.4.3+1
  pubspec_parse: ^1.2.3
  logging: ^1.2.0
  flutter_file_dialog: ^3.0.2
  contentsize_tabbarview:
    git:
      url: https://github.com/Anxcye/contentsize_tabbarview.git
      ref: feat/animation
  wakelock_plus: ^1.2.5
  icons_plus: ^5.0.0
  url_launcher: ^6.2.6
  sqflite_common_ffi: ^2.3.3
  battery_plus: ^6.0.2
  flutter_tts: ^4.0.2
  sticky_headers: ^0.3.0+2
  photo_view: ^0.15.0
  flutter_smart_dialog: ^4.9.8+1
  saver_gallery: ^3.0.6
  share_plus: ^10.0.2
  device_info_plus: ^10.1.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: any
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
#  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/fonts/SourceHanSerifSC-Regular.otf
    - pubspec.yaml
    - assets/foliate-js/
    - assets/foliate-js/vendor/
    - assets/foliate-js/vendor/pdfjs/

  fonts:
    - family: SourceHanSerif
      fonts:
        - asset: assets/fonts/SourceHanSerifSC-Regular.otf

