name: Build Android

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      KEYSTORE_BASE64:
        required: true
      KEYSTORE_PASSWORD:
        required: true
      KEY_PASSWORD:
        required: true
      KEY_ALIAS:
        required: true

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.4'

      - name: Get Dependencies
        run: |
          flutter --version
          flutter pub get

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
          check-latest: true

      - name: Setup Android signing
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks        
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties    
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties    
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties    
          echo "storeFile=keystore.jks" >> android/key.properties

      - name: Build for Android
        run: |
          flutter gen-l10n
          dart run build_runner build --delete-conflicting-outputs
          flutter build apk --release
          flutter build apk --split-per-abi

      - name: Rename builds
        run: |
          cd build/app/outputs/flutter-apk
          mv app-armeabi-v7a-release.apk Anx-Reader-android-${{ inputs.version }}-armeabi-v7a.apk
          mv app-arm64-v8a-release.apk Anx-Reader-android-${{ inputs.version }}-arm64-v8a.apk
          mv app-x86_64-release.apk Anx-Reader-android-${{ inputs.version }}-x86_64.apk
          mv app-release.apk Anx-Reader-android-${{ inputs.version }}-universal.apk

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error