name: Build for App Store Connect

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
    secrets:
      ASC_KEY_ID:
        required: true
      ASC_ISSUER_ID:
        required: true
      ASC_KEY_P8_BASE64:
        required: true
      MATCH_PASSWORD:
        required: true
      MATCH_GIT_BASIC_AUTHORIZATION:
        required: true
      APP_BUNDLE_ID:
        required: true

jobs:
  build-appstore:
    runs-on: macos-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.32.4'  

      - name: check ruby and pod versions
        run: |
          cd ios && bundle install
          which ruby && ruby --version
          which pod && pod --version

      - name: Get Dependencies
        run: |
          sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer
          flutter --version
          # flutter doctor -v
          # flutter pub get
          # dart run build_runner build --delete-conflicting-outputs

      - name: Build iOS App
        timeout-minutes: 20
        run: |
          cd ios
          bundle install
          fastlane ios release_app_store
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8_BASE64: ${{ secrets.ASC_KEY_P8_BASE64 }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}

      - name: Build macos App
        timeout-minutes: 20
        run: |
          cd macos
          bundle install
          fastlane release_app_store
        env:
          ASC_KEY_ID: ${{ secrets.ASC_KEY_ID }}
          ASC_ISSUER_ID: ${{ secrets.ASC_ISSUER_ID }}
          ASC_KEY_P8_BASE64: ${{ secrets.ASC_KEY_P8_BASE64 }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}