name: Build & Release

on:
  push:
    tags:
      - 'v*'
      - 'beta-*'
      - 'alpha-*'

permissions:
  contents: write

jobs:
  setup:
    uses: ./.github/workflows/setup.yaml

  build-android:
    needs: setup
    uses: ./.github/workflows/build-android.yaml
    with:
      version: ${{ needs.setup.outputs.version }}
    secrets:
      KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

  build-ios:
    needs: setup
    uses: ./.github/workflows/build-ios.yaml
    with:
      version: ${{ needs.setup.outputs.version }}

  build-windows:
    needs: setup
    uses: ./.github/workflows/build-windows.yaml
    with:
      version: ${{ needs.setup.outputs.version }}
    secrets:
      SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}

  build-macos:
    needs: setup
    uses: ./.github/workflows/build-macos.yaml
    with:
      version: ${{ needs.setup.outputs.version }}

  build-appstore:
    needs: setup
    uses: ./.github/workflows/build-appstore.yaml
    with:
      version: ${{ needs.setup.outputs.version }}
      is_alpha: ${{ needs.setup.outputs.is_alpha }}
      is_beta: ${{ needs.setup.outputs.is_beta }}
    secrets:
      APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      APP_STORE_CONNECT_API_PRIVATE_KEY: ${{ secrets.APP_STORE_CONNECT_API_PRIVATE_KEY }}
      IOS_DISTRIBUTION_CERTIFICATE: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE }}
      IOS_DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_PASSWORD }}
      IOS_PROVISIONING_PROFILE: ${{ secrets.IOS_PROVISIONING_PROFILE }}
      MACOS_DISTRIBUTION_CERTIFICATE: ${{ secrets.MACOS_DISTRIBUTION_CERTIFICATE }}
      MACOS_DISTRIBUTION_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_DISTRIBUTION_CERTIFICATE_PASSWORD }}
      MACOS_PROVISIONING_PROFILE: ${{ secrets.MACOS_PROVISIONING_PROFILE }}

  release:
    needs: [setup, build-android, build-ios, build-windows, build-macos]
    uses: ./.github/workflows/release.yaml
    with:
      version: ${{ needs.setup.outputs.version }}
      is_alpha: ${{ needs.setup.outputs.is_alpha }}
      is_beta: ${{ needs.setup.outputs.is_beta }}
      release_notes: ${{ needs.setup.outputs.release_notes }}